[tool.poetry]
name = "audible"
version = "0.1.0"
description = ""
authors = ["AlexGazagnes"]
license = "GNU GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.12"
streamlit = "^1.29.0"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"
pytube = "^15.0.0"
youtube-transcript-api = "^0.6.2"


[tool.poetry.group.dev.dependencies]
black = "^23.12.1"
mypy = "^1.8.0"
coverage = "^7.4.0"
flake8 = "^7.0.0"
pep8 = "^1.7.1"
jupyter = "^1.0.0"
notebook = "^7.0.6"
jupyterlab = "^4.0.10"
ipykernel = "^6.28.0"
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
